#$ -S /bin/bash
#$ -N batch_exome
#$ -j yes
#$ -l h_rt=30:00:00
#$ -l h_vmem=8G
#$ -l tmem=8G
#$ -l scratch0free=40G
#### V tells qsub to load your environment
#$ -V

REFDIR=/share/apps/cto/reference/g1kh37/
CAPDIR=/home/sejjctj/capture_files/
SCRIPTDIR=/home/sejjctj/job_scripts/
workplace=$1
bam_list=$2
bai_list=$3
user=$4
reference=human_g1k_v37

echo "$user"
echo "the job is running on the node $HOSTNAME"
echo "job number $JOB_ID"

#########################
# user folder creation  #
#########################

cd /scratch0 || exit
if [ ! -d "$user" ]
then
    echo "####MESS the directory $user on /scratch0/ does not exist: creating it"
    mkdir "$user"
    cd "$user"  || exit
else
    echo "####MESS the directory $user on /scratch0/ exists, moving to it"
    cd "$user" || exit
fi

echo "####MESS I am now in directory"
pwd
echo

#####################################
# cp reference to working directory #
#####################################

cp "$REFDIR"/"$reference".fasta .
ls -l
			
##################
# copy bed file  #
##################

cp "$CAPDIR"/sureselect_ext200.bed .

ls -l
#######################
# job folder creation #
#######################

echo "creating job directory"
mkdir "$JOB_ID"
cd "$JOB_ID"  || exit
echo "####MESS I am now on directory:"
pwd
echo

########################
# copy necessary files #
########################

cp "$workplace"/"$bam_list" .
cp "$workplace"/"$bai_list" .
echo "$PWD"/*

##########################################
# unload generic R and load preferred R  #
##########################################

module unload r
module load r/3.2.2

##################################
# create and execute the Rscript #
##################################

echo "library(ExomeDepth, lib.loc='/share/apps/cto/rlib')
SureLoc <- read.table('../sureselect_ext200.bed', header = TRUE)
source('bam.list')
source('bai.list')
myCount <- getBamCounts(bed.frame = SureLoc, bam.files = my.bam, index.files = my.bai, include.chr = FALSE, referenceFasta = '../human_g1k_v37.fasta')
myCount.dafr <- as(myCount[, colnames(myCount)], 'data.frame')
write.csv(myCount.dafr, 'data_GC.csv') " > simple_counter_GC.R 

echo
echo "### executing R script for coverage"
date

R CMD BATCH simple_counter_GC.R 2>error

###########################
# copy files back
##########################

echo "copying files back"

cp ./*Rout "$workplace"/.
cp ./*csv "$workplace"/.
cp error "$workplace"/.

#############################################
# delete job folder from scratch
#############################################

echo "####MESS moving to /scratch0/$user"
date
cd /scratch0/"$user" || exit
echo "####MESS removing any left file"
rm -r "$JOB_ID"
rm "$reference".fasta

echo "####MESS removal done"
date
echo "### job completed"
date
