#!/bin/bash 
#$ -S /bin/bash
#$ -N sam_merge
#$ -j yes
#$ -l scr=100G
#$ -l h_rt=12:00:00
#$ -l h_vmem=16G
#$ -l tmem=16G
#$ -V

workplace=$1
user=$2
chromosome=$3
sample=$4
output_prefix="$sample"_$chromosome

platform="ILLUMINA"
readgroup="$output_prefix"\.bam
library="GOSgene"
array=( $(ls "$workplace"/lane*/BGI-[0-9][0-9][0-9]\_L00[0-9]\_1.fq.gz.bwa.sorted.REF_"$chromosome"\.bam) )

module load samtools
# I don't load picard-tools as module because I want to give java -jar options

PICARD=/share/apps/cto/packages/Picard-tools/1.140/

echo "---parameters received-----"
echo "workplace " "$workplace"
echo "bams" "${array[@]}"
echo "user " "$user"
echo "output_prefix " "$output_prefix"
echo "==========================="
echo

echo "the job is running on the node $HOSTNAME"
echo "job number $JOB_ID"

#######################################
# user folder creation
######################################
cd /scratch0 || exit
if [ ! -d "$user" ]
then
        echo "####MESS the directory $user on /scratch0/ does not exist: creating it"
        mkdir "$user"
        cd "$user" || exit
        mkdir "$JOB_ID"
        cd "$JOB_ID" || exit
else
        echo "####MESS the directory $user on /scratch0 exists, moving to it"
        cd "$user" || exit
        mkdir "$JOB_ID"
        cd "$JOB_ID" || exit
fi

echo "####MESS I am now on directory:"
pwd
echo

echo "####MESS starting the job and moving to /scratch0/$user/$JOB_ID"
date

#####################
# copy bams local   #
#####################
for i in "${array[@]}"
do
echo "$i"
done
for i in "${array[@]}"
do
cp "$i" .
done

ls
echo "####MESS copy completed"
date

ls

#######################
#    create array     #
#######################

arr=($(ls -f ./*bam))

echo "${arr[@]}"

#######################
## run merge files   ##
#######################

vars=$(printf "%s " "${arr[@]}")
bam1="${arr[0]}"
echo "$vars"

date

echo "samtools merge -cp -h $bam1 $output_prefix.bam $vars"

samtools merge $output_prefix.bam $vars

date

echo "index with samtools"

samtools index "$output_prefix"\.bam

date

ls -l

rm -r tmp
echo "index with samtools"

samtools index "$output_prefix"\.bam
date

#############
# copy back #
#############

cp "$output_prefix"\.bam "$workplace"/.
cp "$output_prefix"\.bam.bai "$workplace"/.

date
echo "####MESS Delete files"

cd ..

rm -r "$JOB_ID"
