#!/bin/bash -l
#Force bash as the executing shell.
#$ -S /bin/bash
#$ -N rel_rec
# Join the error stream to the output stream.
#$ -j yes
#$ -pe smp 4
#$ -l h_rt=12:00:00
#$ -l h_vmem=4G
#$ -l tmem=4G
#$ -l scr=50G
#$ -V

echo "the job is running on the node $HOSTNAME"
echo "job number $JOB_ID"

#parameters to be passed to the job
referencename=$1
workplace=$2
bamfile=$3
interval=$4
user=$5

#################################################################
# where the references, resources and  applications are located #
#################################################################

APPDIR=/share/apps/genomics/GenomeAnalysisTK-3.4-46
REFDIR=/share/apps/cto/reference/g1kh37/
RESDIR=/share/apps/cto/reference/gatk_resources

###############################################
# where the references are located
###############################################

# todo these can be kept as bgzip file gatk can handle that

snps=$RESDIR/dbsnp_138.b37.excluding_sites_after_129.vcf.gz

cd /scratch0 || exit

if [ ! -d "$user" ]
then
	echo "####MESS the directory $user on /scratch0/ does not exist: creating it"
	mkdir "$user"
	cd "$user" || exit
else
	echo "####MESS the directory $user on /scratch0 exists, moving to it"
	cd "$user" || exit
fi

echo "####MESS I am now on directory:"
pwd
echo

##################################
# copy of the reference if needed
##################################

if [ ! -f "$referencename.fasta" ] || [ ! -f "$referencename.fasta.fai" ] || [ ! -f "$referencename.dict" ]

then
	echo "####MESS untaring the reference files to the temporary directory"
	tar -xzf $REFDIR/"$referencename"\.tar.gz -C /scratch0/"$user"/
else
	echo "####MESS the reference already exists in the node"
fi
			
echo "####MESS copy reference completed"
date


##### folder creation ##############
echo "creating the job directory"
mkdir "$JOB_ID"
cd "$JOB_ID" || exit
echo "####MESS I am now on directory:"

pwd


#################################################
# check if intervals file is given
#################################################

# fi interval is given as 0
if [ "$interval" == 0 ]
 then interval=""
# if $interval looks like bed file
elif [[ "$interval" == *"bed" ]]
        then cp "$REFDIR"/"$interval" .
# if interval is given as a chromosome then keep it
elif [[ "$interval" == *"[1-9A-Z]" ]]
    then
    :
fi

##################################
# copy all the files necessary 
##################################

echo "### copying the bamfile"
date
cp "$workplace"/"${bamfile:0:${#bamfile}-1}"? .

if ! [ $? -eq 0 ]
   then
   exit 1
fi 

###################
##  module load  ##
###################

module load samtools

if [ -f "$workplace"/"$bamfile"\.bai ]
	then
	cp "$workplace"/"$bamfile"\.bai .
else
	echo "no bam index found, creating index"
	"$NEWSAMDIR"/samtools index "$bamfile"
fi
echo "### copy completed"
date

echo "### copying the snp file"
date

cp "$snps" .
echo "### copy completed"
date

# check if $intevals is empty
if  [ -z "$interval" ]
   then
        java -Xmx2g -Xms2g  \
    	-jar $APPDIR/GenomeAnalysisTK.jar \
   	-T BaseRecalibrator \
        -nct 8 \
   	-R /scratch0/"$user"/"$referencename"\.fasta \
   	-I "$bamfile" \
   	-knownSites "$snps" \
   	-o "$bamfile"\.recal_data.table
        if [ $? -eq 0 ]
	  then
          echo "recal table creation complete"
          touch "$workplace"/recal_tab_complete
	fi
else 
	java -Xmx2g -Xms2g  \
    	-jar "$APPDIR"/GenomeAnalysisTK.jar \
   	-T BaseRecalibrator \
        -nct 4 \
   	-R /scratch0/"$user"/"$referencename"\.fasta \
   	-I "$bamfile" \
   	-L "$interval" \
        -knownSites "$snps" \
   	-o "$bamfile"\.recal_data.table
        if [ $? -eq 0 ]
	   then
	   echo "recal table creation complete"	
           touch "$workplace"/recal_tab_complete
        fi
fi
############################################################
# copy files back
##########################################################

date

mv "$bamfile"\.recal_data.table "$workplace"/

echo "####MESS moving to /scratch0/$user"
date
cd /scratch0/"$user" || exit
echo "####MESS removing any left file"
rm -r "$JOB_ID"
#########################
### remove references ###
#########################

rm ./human*

echo "####MESS removal done"
date
echo "### job completed"
date
