#!/bin/bash -l
#$ -S /bin/bash
#$ -N csfastqc
#$ -j yes
#$ -l h_rt=03:00:00
#$ -l h_vmem=6G
#$ -l tmem=6G
#$ -l scr=50G
#$ -V


#Assign command line arguments to correct variables

workplace=$1
filename=$2
user=$3


echo "the job is running on the node $HOSTNAME"
echo "job number $JOB_ID"

#######################################
# user folder creation
######################################

cd /scratch0 || exit
if [ ! -d "$user" ]
then
	echo "####MESS the directory $user on /scratch0/ does not exist: creating it"
	mkdir "$user"
	cd "$user" || exit
	mkdir "$JOB_ID"
	cd "$JOB_ID" || exit
else
	echo "####MESS the directory $user on /scratch0 exists, moving to it"
	cd "$user" || exit
	mkdir "$JOB_ID"
	cd "$JOB_ID" || exit
fi

echo "####MESS I am now on directory:"
pwd
echo

# load required module
module load fastqc

echo "####MESS starting the job and moving to /scratch0/$user/$JOB_ID"
date

echo "####MESS copying $workplace/$filename to temp directory"
date
cp "$workplace"/"$filename" .
echo "####MESS copy completed"
date

echo "Starting FastQC on $filename"
date
fastqc "$filename"

echo "####copy back all results"
date

mv ./*fastqc* "$workplace"/

cd /scratch0/"$user" || exit
rm -r "$JOB_ID"
echo "directory $JOB_ID removed"
echo "####MESS Job finished"
date
